### PR TITLE
Persian Translation Submission

### PR DESCRIPTION
**Pull request by wayofmani**
### Hello, or as we say in Persian :
"درود"
 (/doroud/)

I have a translation available at `fa-ir.json` file for Persian language. 

I can assure you that all translations in the app are in common, modern Persian and they all are ok. but maybe you have some issues with translation for hero names cause I've did it but i didn't saw someone else translates hero names. Many Iranians have enjoyed Dota 1 (All-Stars/Warcraft 3) and Dota 2 in gaming cafes and clubs, and because of that they have their own called names for heroes those were inside the game from the 0 day and I've did translated those heroes in that way. 

**1. Localized**
- Night Stalker -> Asghar Shab Ro 
(which is mean "Asghar night stalker", we call him with an extra noun name in beginning "Asghar" - "اصغر")
- Gyrocopter -> Helicopter's pilot
- Ogre Magi -> Dumb Ogre
- Pudge -> Boucher
- Slark -> Stabber Fish
- Templar Assassin -> Temple's Assassin
- Specter -> Ghost
- Tiny -> Mr. Tiny (We call him as Mr. small or Mr. tiny in Persian Mr.="آقا")
- IO -> Soul

 **2. Direct Translations**
 Lina -> `لینا`
 Lich -> `لیچ `
 Kunkka -> `کونکا`
 Huskar -> `هاسکار`
 and etc. 
 
 **3.Literal Translations**
other translations are turned to Persian meaning and Persian words like "death prophet" has turned to 
`death: مرگ
prophet:پیامبر
death prophet: پیامبر مرگ`
but i can change all of these translations like second type of translation, only using Persian letters because it may looks weird, people wouldn't call these heroes in this way casually and they call them like this only for fun but they get what is your mean.

### CODE REVIEW

**Comment by wayofmani** [comment]
Persian is a RTL language, might be makes some issues...

**Comment by andsfonseca** [comment]
Hi @wayofmani, about your translation issues. I don't think it would be a problem to put your translation. For example, here in Brazil, new heroes like Mars and Primal Beast received names translated as "Marte" and "Fera Primal"), although almost no one I know speaks these names, I chose to leave the translation just for testing purposes and did some jokes also like changing the name Wraith King to Skeleton King when using the arcana (removed by the community a few versions ago). So I have no problem leaving your translation, in fact you have my full support for adding your version!

Regarding the fact that it is RTL, I will have to study the behavior, but I should be able to solve any problems (if any) from the next version, nothing to worry about ;)

**Comment by andsfonseca** [comment]
By the way, you can test your translation by placing your json inside the dota2-rpc files and changing the default language manually.

If you want to try it...

**Comment by wayofmani** [comment]
> Hi @wayofmani, about your translation issues. I don't think it would be a problem to put your translation. For example, here in Brazil, new heroes like Mars and Primal Beast received names translated as "Marte" and "Fera Primal"), although almost no one I know speaks these names, I chose to leave the translation just for testing purposes and did some jokes also like changing the name Wraith King to Skeleton King when using the arcana (removed by the community a few versions ago). So I have no problem leaving your translation, in fact you have my full support for adding your version!
> 
> Regarding the fact that it is RTL, I will have to study the behavior, but I should be able to solve any problems (if any) from the next version, nothing to worry about ;)

That's nice to hear about, hope all things works well.

**Review by andsfonseca — APPROVED** [review]

**Pull request merged**
